<a href="https://colab.research.google.com/github/umermaher/DSA-Labs/blob/main/20SW033_Lab04_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

# Task 1
list_array = np.arange(2,33,2)
list_array.reshape(4,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [13]:
# Task 2
fiveDArray = np.arange(1,26)
fiveDArray.reshape(5,5)
oddBooleanIndexing = fiveDArray % 2 != 0

oddArray = fiveDArray[oddBooleanIndexing]
oddArray

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [25]:
#Task 3
broadcastedArray = np.arange(1,5).reshape(1,-1) * np.ones((4,1), dtype = int)
broadcastedArray

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])